# Generated by Django 3.2.7 on 2021-09-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='дата публикации товара')),
                ('name', models.CharField(max_length=128, verbose_name='название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена товара')),
                ('unit_price', models.CharField(choices=[('EUR', 'euro'), ('USD', 'USD'), ('RUB', 'руб.')], default='руб.', max_length=64, verbose_name='ед. цены')),
                ('supplier', models.CharField(max_length=128, verbose_name='имя поставщика')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
